moved to docker compose

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,19 +1,78 @@
-version: "3"
 services:
-  mm-dashboard_phpfpm:
+  mm-dashboard:
     build:
       context: .
       dockerfile: Dockerfile_phpfpm
-    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-dashboard}:${VERSION:-latest}
-  mm-dashboard_nginx:
+    container_name: mm-dashboard
+    user: root
+    command: >
+        sh -c "apk add --no-cache --virtual .build-deps $$PHPIZE_DEPS pcre-dev linux-headers autoconf \
+             pecl channel-update pecl.php.net;\
+             nslookup host.docker.internal || echo '172.172.0.1 host.docker.internal' >> /etc/hosts ;\
+             pecl install xdebug-3.3.2 ;\
+             docker-php-ext-enable xdebug ;\
+             echo 'xdebug.mode=debug' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
+             echo 'xdebug.client_host=host.docker.internal' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
+             echo 'xdebug.client_port=9004' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
+             echo 'xdebug.start_with_request=yes' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
+             echo 'xdebug.log=/var/www/xdebug.log' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ;\
+             php-fpm -e"
+    volumes:
+      - ./src:/var/www/src
+      - ./config:/var/www/config
+      - ./tests:/var/www/tests
+      - ./templates:/var/www/templates
+      - ./assets:/var/www/assets
+    environment:
+      - APP_ENV=dev
+      - APP_DEBUG=1
+      - APP_SECRET=insecure
+      - MARKT_API=http://mm-api-nginx:8080/api/1.1.0/
+      - MM_APP_KEY=insecure
+    ports:
+      - 9002:9000
+    networks:
+      - markten
+    tmpfs:
+      - /var/www/var/log
+      - /var/www/var/cache/dev
+      - /var/www/vendor/tecnickcom/tcpdf/fonts/amsterdamsans
+
+  mm-dashboard-nginx:
     build:
       context: .
       dockerfile: Dockerfile_nginx
-    container_name: salmagundi_markten_mm-dashboard_nginx
-    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-dashboard-nginx}:${VERSION:-latest}
+    container_name: mm-dashboard-nginx
+    # quick fix to prevent permission errors.
+    # Better to use nginx-unpriviliged or create a seperate Dockerfile.dev with root user
+    user: root
+
+    # Fixes fastcgi_pass for nginx without changing the default.template
+    links:
+      - mm-dashboard:mm-dashboard-mm-dashboard
+    depends_on:
+      - mm-dashboard
     command: >
       sh -c "sed -i /'fastcgi_param HTTPS on'/d /tmp/default.template;\
-             envsubst '$$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf;\
              exec nginx -g 'daemon off;'"
+    networks:
+      - markten
     ports:
-      - "127.0.0.1:8092:80"
+      - 8092:8080
+    tmpfs:
+      - /var/cache/nginx
+      - /var/run
+      - /var/log/nginx
+    volumes:
+      - nginx_cache:/var/cache/nginx
+      - nginx_logs:/var/log/nginx
+
+networks:
+  markten:
+    external: true
+volumes:
+  php_cache:
+  php_logs:
+  nginx_cache:
+  nginx_logs:
+
